unit DVIW_dmdata;

interface

uses
  Forms,
  SysUtils, Classes, FMTBcd, DB, SqlExpr, DBClient, Provider,
  DBXCommon,   midaslib,
  IWCompListbox, WideStrings, DBXDevartInterBase,
  FlexCel.Core, Flexcel.XlsAdapter;

type
  TdmdDV = class(TDataModule)
    sqlcDateView: TSQLConnection;
    Querydm: TSQLQuery;
    dspQuery2: TDataSetProvider;
    cdsQuerydm: TClientDataSet;
    dsQuerydm: TDataSource;
    dsQdmSmp: TDataSource;
    QuerydmCOUNTRYABR: TWideStringField;
    QuerydmUNITNAME: TWideStringField;
    QuerydmMATERIALABR: TWideStringField;
    QuerydmISOTOPESYSTEM: TWideStringField;
    QuerydmAPPROACHABR: TWideStringField;
    QuerydmTECHABR: TWideStringField;
    QuerydmINTERPABR: TWideStringField;
    QuerydmPREFLEVEL: TSmallintField;
    QuerydmIAGE: TIntegerField;
    QuerydmIAGEPERROR: TIntegerField;
    QuerydmIAGEMERROR: TIntegerField;
    QuerydmAGEUNITS: TWideStringField;
    QuerydmLITHOLOGY: TWideStringField;
    QuerydmMETHODABR: TWideStringField;
    QuerydmRECORDID: TIntegerField;
    QuerydmCONFIDENTIAL: TIntegerField;
    QuerydmRAGE: TFloatField;
    QuerydmRAGEPERROR: TFloatField;
    QuerydmRAGEMERROR: TFloatField;
    cdsQuerydmCOUNTRYABR: TWideStringField;
    cdsQuerydmUNITNAME: TWideStringField;
    cdsQuerydmMATERIALABR: TWideStringField;
    cdsQuerydmISOTOPESYSTEM: TWideStringField;
    cdsQuerydmAPPROACHABR: TWideStringField;
    cdsQuerydmTECHABR: TWideStringField;
    cdsQuerydmINTERPABR: TWideStringField;
    cdsQuerydmPREFLEVEL: TSmallintField;
    cdsQuerydmIAGE: TIntegerField;
    cdsQuerydmIAGEPERROR: TIntegerField;
    cdsQuerydmIAGEMERROR: TIntegerField;
    cdsQuerydmAGEUNITS: TWideStringField;
    cdsQuerydmLITHOLOGY: TWideStringField;
    cdsQuerydmMETHODABR: TWideStringField;
    cdsQuerydmRECORDID: TIntegerField;
    cdsQuerydmCONFIDENTIAL: TIntegerField;
    cdsQuerydmRAGE: TFloatField;
    cdsQuerydmRAGEPERROR: TFloatField;
    cdsQuerydmRAGEMERROR: TFloatField;
    QdmSmp: TSQLQuery;
    dsQuerydmDB: TDataSource;
    QdmSmpRECORDID: TIntegerField;
    QdmSmpISOSYSTEM: TWideStringField;
    QdmSmpSAMPLENO: TWideStringField;
    QdmSmpFRAC: TWideStringField;
    QdmSmpINCLUDED: TWideStringField;
    cdsQdmSmp: TClientDataSet;
    cdsQdmSmpRECORDID: TIntegerField;
    cdsQdmSmpISOSYSTEM: TWideStringField;
    cdsQdmSmpSAMPLENO: TWideStringField;
    cdsQdmSmpFRAC: TWideStringField;
    cdsQdmSmpINCLUDED: TWideStringField;
    qVariables: TSQLQuery;
    qVariablesVARIABLEABR: TWideStringField;
    qVariablesVARIABLENAME: TWideStringField;
    dspVariables: TDataSetProvider;
    cdsVariables: TClientDataSet;
    dsVariables: TDataSource;
    cdsVariablesVARIABLEABR: TWideStringField;
    cdsVariablesVARIABLENAME: TWideStringField;
    cdsTable1: TClientDataSet;
    qIsoModels: TSQLQuery;
    dspIsoModels: TDataSetProvider;
    cdsIsoModels: TClientDataSet;
    dsIsoModels: TDataSource;
    qIsoModelsMODELID: TWideStringField;
    qIsoModelsISOSYSTEM: TWideStringField;
    qIsoModelsMODELPARAM1: TFloatField;
    qIsoModelsMODELPARAM2: TFloatField;
    qIsoModelsMODELPARAM3: TFloatField;
    qIsoModelsMODELPARAM4: TFloatField;
    qIsoModelsMODELPARAM5: TFloatField;
    qIsoModelsISOSYSTEMNAME: TWideStringField;
    cdsIsoModelsMODELID: TWideStringField;
    cdsIsoModelsISOSYSTEM: TWideStringField;
    cdsIsoModelsMODELPARAM1: TFloatField;
    cdsIsoModelsMODELPARAM2: TFloatField;
    cdsIsoModelsMODELPARAM3: TFloatField;
    cdsIsoModelsMODELPARAM4: TFloatField;
    cdsIsoModelsMODELPARAM5: TFloatField;
    cdsIsoModelsISOSYSTEMNAME: TWideStringField;
    qSmpData: TSQLQuery;
    cdsSmpData: TClientDataSet;
    dsSmpData: TDataSource;
    cdsSmpDataSAMPLENO: TWideStringField;
    cdsSmpDataFRAC: TWideStringField;
    cdsSmpDataISOSYSTEM: TWideStringField;
    cdsSmpDataVARIABLEID: TWideStringField;
    cdsSmpDataDATAVALUE: TFloatField;
    cdsSmpDataNORMALISINGFACTOR: TFloatField;
    cdsSmpDataNORMALISINGSTANDARD: TWideStringField;
    qStandards: TSQLQuery;
    qStandardValues: TSQLQuery;
    qStandardsSTANDARDID: TWideStringField;
    qStandardsSTANDARDNAME: TWideStringField;
    qStandardValuesSTANDARDID: TWideStringField;
    qStandardValuesVARIABLEID: TWideStringField;
    qStandardValuesACCEPTEDVALUE: TFloatField;
    qStandardValuesSTANDARDNAME: TWideStringField;
    dspStandards: TDataSetProvider;
    cdsStandards: TClientDataSet;
    dsStandards: TDataSource;
    dspStandardValues: TDataSetProvider;
    cdsStandardValues: TClientDataSet;
    dsStandardValues: TDataSource;
    cdsStandardsSTANDARDID: TWideStringField;
    cdsStandardsSTANDARDNAME: TWideStringField;
    cdsStandardValuesSTANDARDID: TWideStringField;
    cdsStandardValuesVARIABLEID: TWideStringField;
    cdsStandardValuesACCEPTEDVALUE: TFloatField;
    cdsStandardValuesSTANDARDNAME: TWideStringField;
    qVarVar: TSQLQuery;
    dspVarVar: TDataSetProvider;
    cdsVarVar: TClientDataSet;
    dsVarVar: TDataSource;
    qVarVarVARIABLEID: TWideStringField;
    qVarVarVARIABLENAME: TWideStringField;
    cdsVarVarVARIABLEID: TWideStringField;
    cdsVarVarVARIABLENAME: TWideStringField;
    qStandardValuesVARIABLENAME: TWideStringField;
    cdsStandardValuesVARIABLENAME: TWideStringField;
    dsQdmSmpDB: TDataSource;
    qVarRegTypes: TSQLQuery;
    qVarReg: TSQLQuery;
    qSmpDataX: TSQLQuery;
    qVarRegTypesVARREGTYPEID: TWideStringField;
    qVarRegTypesVARREGTYPE: TWideStringField;
    qVarRegISOSYSTEM: TWideStringField;
    qVarRegVARREGTYPEID: TWideStringField;
    qVarRegVARIABLEID: TWideStringField;
    dspVarRegTypes: TDataSetProvider;
    dspVarReg: TDataSetProvider;
    cdsVarRegTypes: TClientDataSet;
    cdsVarReg: TClientDataSet;
    dsVarRegTypes: TDataSource;
    dsVarReg: TDataSource;
    cdsVarRegTypesVARREGTYPEID: TWideStringField;
    cdsVarRegTypesVARREGTYPE: TWideStringField;
    cdsVarRegISOSYSTEM: TWideStringField;
    cdsVarRegVARREGTYPEID: TWideStringField;
    cdsVarRegVARIABLEID: TWideStringField;
    cdsSmpDataSTANDARDVALUE: TFloatField;
    cdsSmpDataX: TClientDataSet;
    dsSmpDataX: TDataSource;
    qSmpDataXerr: TSQLQuery;
    cdsSmpDataXerr: TClientDataSet;
    dsSmpDataXerr: TDataSource;
    cdsQdmSmpqSmpDataXerr: TDataSetField;
    cdsSmpDataXerrVARIABLEID: TWideStringField;
    cdsSmpDataXerrDATAVALUE: TFloatField;
    cdsSmpDataXerrNORMALISINGSTANDARD: TWideStringField;
    cdsSmpDataXerrSTANDARDVALUE: TFloatField;
    cdsSmpDataXerrVARIABLENAME: TWideStringField;
    dspQdmSmp: TDataSetProvider;
    qStandardValueX: TSQLQuery;
    dsqSmpDataX: TDataSource;
    cdsAcceptedValueX: TClientDataSet;
    dsAcceptedValueX: TDataSource;
    qSmpDataY: TSQLQuery;
    dsqSmpDataY: TDataSource;
    cdsSmpDataY: TClientDataSet;
    StringField1: TWideStringField;
    FloatField1: TFloatField;
    StringField2: TWideStringField;
    FloatField2: TFloatField;
    StringField3: TWideStringField;
    StringField4: TWideStringField;
    StringField5: TWideStringField;
    StringField6: TWideStringField;
    dsSmpDataY: TDataSource;
    qStandardValueY: TSQLQuery;
    cdsAcceptedValueY: TClientDataSet;
    FloatField3: TFloatField;
    dsAcceptedValueY: TDataSource;
    cdsQdmSmpqSmpDataY: TDataSetField;
    qSmpDataYerr: TSQLQuery;
    cdsSmpDataYerr: TClientDataSet;
    StringField8: TWideStringField;
    FloatField4: TFloatField;
    StringField9: TWideStringField;
    FloatField5: TFloatField;
    StringField10: TWideStringField;
    dsSmpDataYerr: TDataSource;
    qSmpDataR: TSQLQuery;
    cdsSmpDataR: TClientDataSet;
    StringField11: TWideStringField;
    FloatField6: TFloatField;
    StringField12: TWideStringField;
    FloatField7: TFloatField;
    StringField13: TWideStringField;
    dsSmpDataR: TDataSource;
    cdsQdmSmpqSmpDataR: TDataSetField;
    cdsQdmSmpqSmpDataYerr: TDataSetField;
    cdsSmpDataXSAMPLENO: TWideStringField;
    cdsSmpDataXFRAC: TWideStringField;
    cdsSmpDataXISOSYSTEM: TWideStringField;
    cdsSmpDataXVARIABLEID: TWideStringField;
    cdsSmpDataXDATAVALUE: TFloatField;
    cdsSmpDataXNORMALISINGSTANDARD: TWideStringField;
    cdsSmpDataXSTANDARDVALUE: TFloatField;
    cdsSmpDataXVARIABLENAME: TWideStringField;
    cdsSmpDataXqStandardValueX: TDataSetField;
    qNormalisedValueX: TSQLQuery;
    cdsNormalisedValueX: TClientDataSet;
    dsNormalisedValueX: TDataSource;
    qNormalisedValueY: TSQLQuery;
    cdsNormalisedValueY: TClientDataSet;
    dsNormalisedValueY: TDataSource;
    cdsAcceptedValueXACCEPTEDVALUE: TFloatField;
    cdsNormalisedValueXNORMALISEDVALUE: TFloatField;
    cdsNormalisedValueYNORMALISEDVALUE: TFloatField;
    qErrTypeX: TSQLQuery;
    cdsErrTypeX: TClientDataSet;
    dsErrTypeX: TDataSource;
    dsqSmpDataXerr: TDataSource;
    qErrTypeY: TSQLQuery;
    cdsErrTypeY: TClientDataSet;
    dsErrTypeY: TDataSource;
    dsqSmpDataYerr: TDataSource;
    qSmpDataPrecX: TSQLQuery;
    cdsSmpDataPrecX: TClientDataSet;
    dsSmpDataPrecX: TDataSource;
    cdsQdmSmpqSmpDataPrecX: TDataSetField;
    cdsSmpDataPrecXVARIABLEID: TWideStringField;
    cdsSmpDataPrecXDATAVALUE: TFloatField;
    qSmpDataPrecY: TSQLQuery;
    cdsSmpDataPrecY: TClientDataSet;
    StringField7: TWideStringField;
    FloatField8: TFloatField;
    dsSmpDataPrecY: TDataSource;
    cdsQdmSmpqSmpDataPrecY: TDataSetField;
    qErrTypes: TSQLQuery;
    dspErrTypes: TDataSetProvider;
    cdsErrTypes: TClientDataSet;
    dsErrTypes: TDataSource;
    cdsErrTypesERRORTYPE: TWideStringField;
    cdsErrTypesDATAVALUE: TFloatField;
    cdsQdmSmpqErrTypeX: TDataSetField;
    cdsErrTypeXVARIABLEID: TWideStringField;
    cdsErrTypeXDATAVALUE: TFloatField;
    cdsQdmSmpqErrTypeY: TDataSetField;
    cdsErrTypeYVARIABLEID: TWideStringField;
    cdsErrTypeYDATAVALUE: TFloatField;
    cdsQdmSmpqNormalisedValueY: TDataSetField;
    cdsQdmSmpqNormalisedValueX: TDataSetField;
    qSmpDataZ: TSQLQuery;
    dsqSmpDataZ: TDataSource;
    cdsSmpDataZ: TClientDataSet;
    StringField14: TWideStringField;
    FloatField9: TFloatField;
    StringField15: TWideStringField;
    FloatField10: TFloatField;
    StringField16: TWideStringField;
    StringField17: TWideStringField;
    StringField18: TWideStringField;
    StringField19: TWideStringField;
    dsSmpDataZ: TDataSource;
    qStandardValueZ: TSQLQuery;
    cdsAcceptedValueZ: TClientDataSet;
    FloatField11: TFloatField;
    dsAcceptedValueZ: TDataSource;
    qNormalisedValueZ: TSQLQuery;
    cdsNormalisedValueZ: TClientDataSet;
    FloatField12: TFloatField;
    dsNormalisedValueZ: TDataSource;
    qSmpDataPrecZ: TSQLQuery;
    cdsSmpDataPrecZ: TClientDataSet;
    StringField20: TWideStringField;
    FloatField13: TFloatField;
    dsSmpDataPrecZ: TDataSource;
    qSmpDataZerr: TSQLQuery;
    cdsSmpDataZerr: TClientDataSet;
    StringField21: TWideStringField;
    FloatField14: TFloatField;
    StringField22: TWideStringField;
    FloatField15: TFloatField;
    StringField23: TWideStringField;
    dsSmpDataZerr: TDataSource;
    qErrTypeZ: TSQLQuery;
    cdsErrTypeZ: TClientDataSet;
    StringField24: TWideStringField;
    FloatField16: TFloatField;
    dsErrTypeZ: TDataSource;
    cdsQdmSmpqErrTypeZ: TDataSetField;
    cdsQdmSmpqSmpDataZerr: TDataSetField;
    cdsQdmSmpqSmpDataPrecZ: TDataSetField;
    cdsQdmSmpqNormalisedValueZ: TDataSetField;
    cdsQdmSmpqSmpDataZ: TDataSetField;
    cdsSmpDataZqStandardValueZ: TDataSetField;
    QuerydmUNITID: TIntegerField;
    cdsQuerydmUNITID: TIntegerField;
    qSamplesWithData: TSQLQuery;
    dspSamplesWithData: TDataSetProvider;
    cdsSamplesWithData: TClientDataSet;
    dsSamplesWithData: TDataSource;
    cdsSamplesWithDataSAMPLENO: TWideStringField;
    qRawSmp: TSQLQuery;
    dsqRawSmp: TDataSource;
    dspRawSmp: TDataSetProvider;
    cdsRawSmp: TClientDataSet;
    dsRawSmp: TDataSource;
    qRawDataX: TSQLQuery;
    dsqRawDataX: TDataSource;
    cdsRawDataX: TClientDataSet;
    dsRawDataX: TDataSource;
    qRawStandardValueX: TSQLQuery;
    cdsRawStandardValueX: TClientDataSet;
    dsRawStandardValueX: TDataSource;
    qRawNormalisedValueX: TSQLQuery;
    cdsRawNormalisedValueX: TClientDataSet;
    dsRawNormalisedValueX: TDataSource;
    qRawDataXerr: TSQLQuery;
    dsqRawDataXerr: TDataSource;
    cdsRawDataXerr: TClientDataSet;
    dsRawDataXerr: TDataSource;
    qRawErrTypeX: TSQLQuery;
    cdsRawErrTypeX: TClientDataSet;
    dsRawErrTypeX: TDataSource;
    qRawDataPrecX: TSQLQuery;
    cdsRawDataPrecX: TClientDataSet;
    dsRawDataPrecX: TDataSource;
    qRawDataY: TSQLQuery;
    dsqRawDataY: TDataSource;
    cdsRawDataY: TClientDataSet;
    dsRawDataY: TDataSource;
    qRawStandardValueY: TSQLQuery;
    cdsRawStandardValueY: TClientDataSet;
    dsRawStandardValueY: TDataSource;
    qRawNormalisedValueY: TSQLQuery;
    cdsRawNormalisedValueY: TClientDataSet;
    dsRawNormalisedValueY: TDataSource;
    qRawDataYerr: TSQLQuery;
    dsqRawDataYerr: TDataSource;
    cdsRawDataYerr: TClientDataSet;
    dsRawDataYerr: TDataSource;
    qRawErrTypeY: TSQLQuery;
    cdsRawErrTypeY: TClientDataSet;
    dsRawErrTypeY: TDataSource;
    qRawDataPrecY: TSQLQuery;
    cdsRawDataPrecY: TClientDataSet;
    dsRawDataPrecY: TDataSource;
    qRawDataR: TSQLQuery;
    cdsRawDataR: TClientDataSet;
    qRawDataZ: TSQLQuery;
    dsqRawDataZ: TDataSource;
    cdsRawDataZ: TClientDataSet;
    dsRawDataZ: TDataSource;
    dsRawDataR: TDataSource;
    qRawStandardValueZ: TSQLQuery;
    cdsRawStandardValueZ: TClientDataSet;
    dsRawStandardValueZ: TDataSource;
    qRawNormalisedValueZ: TSQLQuery;
    cdsRawNormalisedValueZ: TClientDataSet;
    dsRawNormalisedValueZ: TDataSource;
    qRawDataZerr: TSQLQuery;
    cdsRawDataZerr: TClientDataSet;
    dsRawDataZerr: TDataSource;
    qRawErrTypeZ: TSQLQuery;
    cdsRawErrTypeZ: TClientDataSet;
    dsRawErrTypeZ: TDataSource;
    qRawDataPrecZ: TSQLQuery;
    cdsRawDataPrecZ: TClientDataSet;
    dsRawDataPrecZ: TDataSource;
    cdsRawSmpSAMPLENO: TWideStringField;
    cdsRawSmpFRAC: TWideStringField;
    cdsRawSmpqRawDataXerr: TDataSetField;
    cdsRawSmpqRawDataX: TDataSetField;
    cdsRawSmpqRawDataR: TDataSetField;
    cdsRawSmpqRawErrTypeY: TDataSetField;
    cdsRawSmpqRawErrTypeZ: TDataSetField;
    cdsRawSmpqRawNormalisedValueZ: TDataSetField;
    cdsRawSmpqRawNormalisedValueY: TDataSetField;
    cdsRawSmpqRawDataPrecZ: TDataSetField;
    cdsRawSmpqRawDataZerr: TDataSetField;
    cdsRawSmpqRawDataZ: TDataSetField;
    cdsRawSmpqRawDataPrecY: TDataSetField;
    cdsRawSmpqRawDataYerr: TDataSetField;
    cdsRawSmpqRawDataY: TDataSetField;
    cdsRawSmpqRawDataPrecX: TDataSetField;
    cdsRawSmpqRawNormalisedValueX: TDataSetField;
    cdsRawDataXSAMPLENO: TWideStringField;
    cdsRawDataXFRAC: TWideStringField;
    cdsRawDataXISOSYSTEM: TWideStringField;
    cdsRawDataXVARIABLEID: TWideStringField;
    cdsRawDataXDATAVALUE: TFloatField;
    cdsRawDataXNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataXSTANDARDVALUE: TFloatField;
    cdsRawDataXVARIABLENAME: TWideStringField;
    cdsRawDataXqRawStandardValueX: TDataSetField;
    cdsRawStandardValueXACCEPTEDVALUE: TFloatField;
    cdsRawNormalisedValueXSAMPLENO: TWideStringField;
    cdsRawNormalisedValueXFRAC: TWideStringField;
    cdsRawNormalisedValueXISOSYSTEM: TWideStringField;
    cdsRawNormalisedValueXVARIABLEID: TWideStringField;
    cdsRawNormalisedValueXDATAVALUE: TFloatField;
    cdsRawNormalisedValueXNORMALISINGSTANDARD: TWideStringField;
    cdsRawNormalisedValueXSTANDARDVALUE: TFloatField;
    cdsRawNormalisedValueXACCEPTEDVALUE: TFloatField;
    cdsRawNormalisedValueXNORMALISEDVALUE: TFloatField;
    cdsRawSmpqRawErrTypeX: TDataSetField;
    cdsRawErrTypeXSAMPLENO: TWideStringField;
    cdsRawErrTypeXFRAC: TWideStringField;
    cdsRawErrTypeXISOSYSTEM: TWideStringField;
    cdsRawErrTypeXVARIABLEID: TWideStringField;
    cdsRawErrTypeXDATAVALUE: TFloatField;
    cdsRawErrTypeXNORMALISINGSTANDARD: TWideStringField;
    cdsRawErrTypeXSTANDARDVALUE: TFloatField;
    cdsRawErrTypeXVARIABLENAME: TWideStringField;
    cdsRawDataYSAMPLENO: TWideStringField;
    cdsRawDataYFRAC: TWideStringField;
    cdsRawDataYISOSYSTEM: TWideStringField;
    cdsRawDataYVARIABLEID: TWideStringField;
    cdsRawDataYDATAVALUE: TFloatField;
    cdsRawDataYNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataYSTANDARDVALUE: TFloatField;
    cdsRawDataYVARIABLENAME: TWideStringField;
    cdsRawDataYqRawStandardValueY: TDataSetField;
    cdsRawStandardValueYACCEPTEDVALUE: TFloatField;
    cdsRawNormalisedValueYSAMPLENO: TWideStringField;
    cdsRawNormalisedValueYFRAC: TWideStringField;
    cdsRawNormalisedValueYISOSYSTEM: TWideStringField;
    cdsRawNormalisedValueYVARIABLEID: TWideStringField;
    cdsRawNormalisedValueYDATAVALUE: TFloatField;
    cdsRawNormalisedValueYNORMALISINGSTANDARD: TWideStringField;
    cdsRawNormalisedValueYSTANDARDVALUE: TFloatField;
    cdsRawNormalisedValueYACCEPTEDVALUE: TFloatField;
    cdsRawNormalisedValueYNORMALISEDVALUE: TFloatField;
    cdsRawDataYerrSAMPLENO: TWideStringField;
    cdsRawDataYerrFRAC: TWideStringField;
    cdsRawDataYerrISOSYSTEM: TWideStringField;
    cdsRawDataYerrVARIABLEID: TWideStringField;
    cdsRawDataYerrDATAVALUE: TFloatField;
    cdsRawDataYerrNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataYerrSTANDARDVALUE: TFloatField;
    cdsRawDataYerrVARIABLENAME: TWideStringField;
    cdsRawErrTypeYSAMPLENO: TWideStringField;
    cdsRawErrTypeYFRAC: TWideStringField;
    cdsRawErrTypeYISOSYSTEM: TWideStringField;
    cdsRawErrTypeYVARIABLEID: TWideStringField;
    cdsRawErrTypeYDATAVALUE: TFloatField;
    cdsRawErrTypeYNORMALISINGSTANDARD: TWideStringField;
    cdsRawErrTypeYSTANDARDVALUE: TFloatField;
    cdsRawErrTypeYVARIABLENAME: TWideStringField;
    cdsRawDataPrecYSAMPLENO: TWideStringField;
    cdsRawDataPrecYFRAC: TWideStringField;
    cdsRawDataPrecYISOSYSTEM: TWideStringField;
    cdsRawDataPrecYVARIABLEID: TWideStringField;
    cdsRawDataPrecYDATAVALUE: TFloatField;
    cdsRawDataRSAMPLENO: TWideStringField;
    cdsRawDataRFRAC: TWideStringField;
    cdsRawDataRISOSYSTEM: TWideStringField;
    cdsRawDataRVARIABLEID: TWideStringField;
    cdsRawDataRDATAVALUE: TFloatField;
    cdsRawDataRNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataRSTANDARDVALUE: TFloatField;
    cdsRawDataRVARIABLENAME: TWideStringField;
    cdsRawDataZSAMPLENO: TWideStringField;
    cdsRawDataZFRAC: TWideStringField;
    cdsRawDataZISOSYSTEM: TWideStringField;
    cdsRawDataZVARIABLEID: TWideStringField;
    cdsRawDataZDATAVALUE: TFloatField;
    cdsRawDataZNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataZSTANDARDVALUE: TFloatField;
    cdsRawDataZVARIABLENAME: TWideStringField;
    cdsRawDataZqRawStandardValueZ: TDataSetField;
    cdsRawStandardValueZACCEPTEDVALUE: TFloatField;
    cdsRawNormalisedValueZSAMPLENO: TWideStringField;
    cdsRawNormalisedValueZFRAC: TWideStringField;
    cdsRawNormalisedValueZISOSYSTEM: TWideStringField;
    cdsRawNormalisedValueZVARIABLEID: TWideStringField;
    cdsRawNormalisedValueZDATAVALUE: TFloatField;
    cdsRawNormalisedValueZNORMALISINGSTANDARD: TWideStringField;
    cdsRawNormalisedValueZSTANDARDVALUE: TFloatField;
    cdsRawNormalisedValueZACCEPTEDVALUE: TFloatField;
    cdsRawNormalisedValueZNORMALISEDVALUE: TFloatField;
    cdsRawDataZerrSAMPLENO: TWideStringField;
    cdsRawDataZerrFRAC: TWideStringField;
    cdsRawDataZerrISOSYSTEM: TWideStringField;
    cdsRawDataZerrVARIABLEID: TWideStringField;
    cdsRawDataZerrDATAVALUE: TFloatField;
    cdsRawDataZerrNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataZerrSTANDARDVALUE: TFloatField;
    cdsRawDataZerrVARIABLENAME: TWideStringField;
    cdsRawErrTypeZSAMPLENO: TWideStringField;
    cdsRawErrTypeZFRAC: TWideStringField;
    cdsRawErrTypeZISOSYSTEM: TWideStringField;
    cdsRawErrTypeZVARIABLEID: TWideStringField;
    cdsRawErrTypeZDATAVALUE: TFloatField;
    cdsRawErrTypeZNORMALISINGSTANDARD: TWideStringField;
    cdsRawErrTypeZSTANDARDVALUE: TFloatField;
    cdsRawErrTypeZVARIABLENAME: TWideStringField;
    cdsRawDataPrecZSAMPLENO: TWideStringField;
    cdsRawDataPrecZFRAC: TWideStringField;
    cdsRawDataPrecZISOSYSTEM: TWideStringField;
    cdsRawDataPrecZVARIABLEID: TWideStringField;
    cdsRawDataPrecZDATAVALUE: TFloatField;
    cdsData: TClientDataSet;
    dsData: TDataSource;
    cdsDataSampleNo: TWideStringField;
    cdsDataFrac: TWideStringField;
    cdsDataPb207U235: TFloatField;
    cdsDataPb207U235Sigma: TFloatField;
    cdsDataPb206U238: TFloatField;
    cdsDataU238Pb206: TFloatField;
    cdsDataU238Pb206Sigma: TFloatField;
    cdsDataPb207Pb206: TFloatField;
    cdsDataPb207Pb206Sigma: TFloatField;
    cdsDataIncludeYN: TWideStringField;
    cdsDataPb206U238Sigma: TFloatField;
    qRawDiscordance: TSQLQuery;
    cdsRawDiscordance: TClientDataSet;
    dsRawDiscordance: TDataSource;
    qRawAgePref: TSQLQuery;
    cdsRawAgePref: TClientDataSet;
    dsRawAgePref: TDataSource;
    dsqRawAgePref: TDataSource;
    qRawDataAgeerr: TSQLQuery;
    dsqRawDataAgeerr: TDataSource;
    cdsRawDataAgeerr: TClientDataSet;
    dsRawDataAgeerr: TDataSource;
    cdsRawSmpqRawAgePref: TDataSetField;
    cdsRawSmpqRawDiscordance: TDataSetField;
    cdsRawDiscordanceSAMPLENO: TWideStringField;
    cdsRawDiscordanceFRAC: TWideStringField;
    cdsRawDiscordanceISOSYSTEM: TWideStringField;
    cdsRawDiscordanceVARIABLEID: TWideStringField;
    cdsRawDiscordanceDATAVALUE: TFloatField;
    cdsRawAgePrefSAMPLENO: TWideStringField;
    cdsRawAgePrefFRAC: TWideStringField;
    cdsRawAgePrefISOSYSTEM: TWideStringField;
    cdsRawAgePrefVARIABLEID: TWideStringField;
    cdsRawAgePrefDATAVALUE: TFloatField;
    cdsRawAgePrefqRawDataAgeerr: TDataSetField;
    cdsRawDataAgeerrSAMPLENO: TWideStringField;
    cdsRawDataAgeerrFRAC: TWideStringField;
    cdsRawDataAgeerrISOSYSTEM: TWideStringField;
    cdsRawDataAgeerrVARIABLEID: TWideStringField;
    cdsRawDataAgeerrDATAVALUE: TFloatField;
    cdsRawDataAgeerrNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataAgeerrSTANDARDVALUE: TFloatField;
    cdsRawDataAgeerrVARIABLENAME: TWideStringField;
    cdsDataPercentConcordance: TFloatField;
    cdsDataPreferredAge: TFloatField;
    cdsDataPreferredAgeSigma: TFloatField;
    cdsRawDataXerrSAMPLENO: TWideStringField;
    cdsRawDataXerrFRAC: TWideStringField;
    cdsRawDataXerrISOSYSTEM: TWideStringField;
    cdsRawDataXerrVARIABLEID: TWideStringField;
    cdsRawDataXerrDATAVALUE: TFloatField;
    cdsRawDataXerrNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataXerrSTANDARDVALUE: TFloatField;
    cdsRawDataXerrVARIABLENAME: TWideStringField;
    cdsRawDataPrecXSAMPLENO: TWideStringField;
    cdsRawDataPrecXFRAC: TWideStringField;
    cdsRawDataPrecXISOSYSTEM: TWideStringField;
    cdsRawDataPrecXVARIABLEID: TWideStringField;
    cdsRawDataPrecXDATAVALUE: TFloatField;
    cdsPDF: TClientDataSet;
    cdsPDFStep: TIntegerField;
    cdsPDFPDFDataValue: TFloatField;
    cdsPDFPDFValue: TFloatField;
    dsPDF: TDataSource;
    cdsPeaksFound: TClientDataSet;
    dsPeaksFound: TDataSource;
    cdsPeaksFoundi: TIntegerField;
    cdsPeaksFoundAge: TFloatField;
    cdsPeaksFoundAgePlus95: TFloatField;
    cdsPeaksFoundAgeMinus95: TFloatField;
    cdsPeaksFoundProbability: TFloatField;
    qRawRef: TSQLQuery;
    cdsRawRef: TClientDataSet;
    dsRawRef: TDataSource;
    cdsRawSmpqRawRef: TDataSetField;
    cdsRawRefSAMPLENO: TWideStringField;
    cdsRawRefREFNUM: TIntegerField;
    cdsRawRefSOURCESHORT: TWideStringField;
    qRawSmpLoc: TSQLQuery;
    cdsRawSmpLoc: TClientDataSet;
    dsRawSmpLoc: TDataSource;
    cdsRawSmpqRawSmpLoc: TDataSetField;
    cdsRawSmpLocCOUNTRYABR: TWideStringField;
    cdsRawSmpLocCONTINENTID: TWideStringField;
    cdsRawSmpLocLONGITUDE: TFloatField;
    cdsRawSmpLocLATITUDE: TFloatField;
    cdsRawSmpLocELEVATION: TFloatField;
    dsDataHf: TDataSource;
    cdsDataHf: TClientDataSet;
    cdsDataHfSampleNo: TWideStringField;
    cdsDataHfFrac: TWideStringField;
    cdsDataHfEpsilon: TFloatField;
    cdsDataHfEpsilonSigma: TFloatField;
    cdsDataHfPreferredAge: TFloatField;
    cdsDataHfPreferredAgeSigma: TFloatField;
    cdsDataHfIncludeYN: TWideStringField;
    cdsDataHfPercentConcordance: TFloatField;
    cdsDataHfTDM: TFloatField;
    cdsDataHfTDMSigma: TFloatField;
    qRawDataDM: TSQLQuery;
    dsqRawDataDM: TDataSource;
    cdsRawDataDM: TClientDataSet;
    dsRawDataDM: TDataSource;
    qRawDataDMerr: TSQLQuery;
    dsqRawDataDMerr: TDataSource;
    cdsRawDataDMerr: TClientDataSet;
    dsRawDataDMerr: TDataSource;
    cdsRawSmpqRawDataDM: TDataSetField;
    cdsRawDataDMSAMPLENO: TWideStringField;
    cdsRawDataDMFRAC: TWideStringField;
    cdsRawDataDMISOSYSTEM: TWideStringField;
    cdsRawDataDMVARIABLEID: TWideStringField;
    cdsRawDataDMDATAVALUE: TFloatField;
    cdsRawDataDMqRawDataDMerr: TDataSetField;
    cdsRawDataDMerrSAMPLENO: TWideStringField;
    cdsRawDataDMerrFRAC: TWideStringField;
    cdsRawDataDMerrISOSYSTEM: TWideStringField;
    cdsRawDataDMerrVARIABLEID: TWideStringField;
    cdsRawDataDMerrDATAVALUE: TFloatField;
    cdsRawDataDMerrNORMALISINGSTANDARD: TWideStringField;
    cdsRawDataDMerrSTANDARDVALUE: TFloatField;
    cdsRawDataDMerrVARIABLENAME: TWideStringField;
    qExisting: TSQLQuery;
    dspExisting: TDataSetProvider;
    cdsExisting: TClientDataSet;
    dsExisting: TDataSource;
    cdsExistingRECORDID: TIntegerField;
    cdsExistingCOUNTRYABR: TWideStringField;
    cdsExistingUNITID: TIntegerField;
    cdsExistingMATERIALABR: TWideStringField;
    cdsExistingISOTOPESYSTEM: TWideStringField;
    cdsExistingAPPROACHABR: TWideStringField;
    cdsExistingTECHABR: TWideStringField;
    cdsExistingINTERPABR: TWideStringField;
    cdsExistingRAGE: TFloatField;
    cdsExistingRAGEPERROR: TFloatField;
    cdsExistingRAGEMERROR: TFloatField;
    cdsExistingUNITNAME: TWideStringField;
    cdsExistingUNITRANK: TWideStringField;
    cdsExistingCONTINENTID: TWideStringField;
    cdsExistingMATERIALDESCRIPTION: TWideStringField;
    cdsExistingAPPROACHDESCRIPTION: TWideStringField;
    cdsExistingTECHNIQUE: TWideStringField;
    cdsExistingINTERPRETATION: TWideStringField;
    qRawDataZSAMPLENO: TWideStringField;
    qRawDataZFRAC: TWideStringField;
    qRawDataZISOSYSTEM: TWideStringField;
    qRawDataZVARIABLEID: TWideStringField;
    qRawDataZDATAVALUE: TFloatField;
    qRawDataZNORMALISINGSTANDARD: TWideStringField;
    qRawDataZSTANDARDVALUE: TFloatField;
    qRawDataZVARIABLENAME: TWideStringField;
    qRawSmpSAMPLENO: TWideStringField;
    qRawSmpFRAC: TWideStringField;
    qRawDataXSAMPLENO: TWideStringField;
    qRawDataXFRAC: TWideStringField;
    qRawDataXISOSYSTEM: TWideStringField;
    qRawDataXVARIABLEID: TWideStringField;
    qRawDataXDATAVALUE: TFloatField;
    qRawDataXNORMALISINGSTANDARD: TWideStringField;
    qRawDataXSTANDARDVALUE: TFloatField;
    qRawDataXVARIABLENAME: TWideStringField;
    qRawStandardValueXACCEPTEDVALUE: TFloatField;
    qRawNormalisedValueXSAMPLENO: TWideStringField;
    qRawNormalisedValueXFRAC: TWideStringField;
    qRawNormalisedValueXISOSYSTEM: TWideStringField;
    qRawNormalisedValueXVARIABLEID: TWideStringField;
    qRawNormalisedValueXDATAVALUE: TFloatField;
    qRawNormalisedValueXNORMALISINGSTANDARD: TWideStringField;
    qRawNormalisedValueXSTANDARDVALUE: TFloatField;
    qRawNormalisedValueXACCEPTEDVALUE: TFloatField;
    qRawNormalisedValueXNORMALISEDVALUE: TFloatField;
    qRawDataXerrSAMPLENO: TWideStringField;
    qRawDataXerrFRAC: TWideStringField;
    qRawDataXerrISOSYSTEM: TWideStringField;
    qRawDataXerrVARIABLEID: TWideStringField;
    qRawDataXerrDATAVALUE: TFloatField;
    qRawDataXerrNORMALISINGSTANDARD: TWideStringField;
    qRawDataXerrSTANDARDVALUE: TFloatField;
    qRawDataXerrVARIABLENAME: TWideStringField;
    qRawErrTypeXSAMPLENO: TWideStringField;
    qRawErrTypeXFRAC: TWideStringField;
    qRawErrTypeXISOSYSTEM: TWideStringField;
    qRawErrTypeXVARIABLEID: TWideStringField;
    qRawErrTypeXDATAVALUE: TFloatField;
    qRawErrTypeXNORMALISINGSTANDARD: TWideStringField;
    qRawErrTypeXSTANDARDVALUE: TFloatField;
    qRawErrTypeXVARIABLENAME: TWideStringField;
    qRawDataPrecXSAMPLENO: TWideStringField;
    qRawDataPrecXFRAC: TWideStringField;
    qRawDataPrecXISOSYSTEM: TWideStringField;
    qRawDataPrecXVARIABLEID: TWideStringField;
    qRawDataPrecXDATAVALUE: TFloatField;
    qRawDataYSAMPLENO: TWideStringField;
    qRawDataYFRAC: TWideStringField;
    qRawDataYISOSYSTEM: TWideStringField;
    qRawDataYVARIABLEID: TWideStringField;
    qRawDataYDATAVALUE: TFloatField;
    qRawDataYNORMALISINGSTANDARD: TWideStringField;
    qRawDataYSTANDARDVALUE: TFloatField;
    qRawDataYVARIABLENAME: TWideStringField;
    qRawStandardValueYACCEPTEDVALUE: TFloatField;
    qRawNormalisedValueYSAMPLENO: TWideStringField;
    qRawNormalisedValueYFRAC: TWideStringField;
    qRawNormalisedValueYISOSYSTEM: TWideStringField;
    qRawNormalisedValueYVARIABLEID: TWideStringField;
    qRawNormalisedValueYDATAVALUE: TFloatField;
    qRawNormalisedValueYNORMALISINGSTANDARD: TWideStringField;
    qRawNormalisedValueYSTANDARDVALUE: TFloatField;
    qRawNormalisedValueYACCEPTEDVALUE: TFloatField;
    qRawNormalisedValueYNORMALISEDVALUE: TFloatField;
    qRawDataYerrSAMPLENO: TWideStringField;
    qRawDataYerrFRAC: TWideStringField;
    qRawDataYerrISOSYSTEM: TWideStringField;
    qRawDataYerrVARIABLEID: TWideStringField;
    qRawDataYerrDATAVALUE: TFloatField;
    qRawDataYerrNORMALISINGSTANDARD: TWideStringField;
    qRawDataYerrSTANDARDVALUE: TFloatField;
    qRawDataYerrVARIABLENAME: TWideStringField;
    qRawDataRSAMPLENO: TWideStringField;
    qRawDataRFRAC: TWideStringField;
    qRawDataRISOSYSTEM: TWideStringField;
    qRawDataRVARIABLEID: TWideStringField;
    qRawDataRDATAVALUE: TFloatField;
    qRawDataRNORMALISINGSTANDARD: TWideStringField;
    qRawDataRSTANDARDVALUE: TFloatField;
    qRawDataRVARIABLENAME: TWideStringField;
    qRawDataPrecYSAMPLENO: TWideStringField;
    qRawDataPrecYFRAC: TWideStringField;
    qRawDataPrecYISOSYSTEM: TWideStringField;
    qRawDataPrecYVARIABLEID: TWideStringField;
    qRawDataPrecYDATAVALUE: TFloatField;
    qRawErrTypeYSAMPLENO: TWideStringField;
    qRawErrTypeYFRAC: TWideStringField;
    qRawErrTypeYISOSYSTEM: TWideStringField;
    qRawErrTypeYVARIABLEID: TWideStringField;
    qRawErrTypeYDATAVALUE: TFloatField;
    qRawErrTypeYNORMALISINGSTANDARD: TWideStringField;
    qRawErrTypeYSTANDARDVALUE: TFloatField;
    qRawErrTypeYVARIABLENAME: TWideStringField;
    qRawStandardValueZACCEPTEDVALUE: TFloatField;
    qRawNormalisedValueZSAMPLENO: TWideStringField;
    qRawNormalisedValueZFRAC: TWideStringField;
    qRawNormalisedValueZISOSYSTEM: TWideStringField;
    qRawNormalisedValueZVARIABLEID: TWideStringField;
    qRawNormalisedValueZDATAVALUE: TFloatField;
    qRawNormalisedValueZNORMALISINGSTANDARD: TWideStringField;
    qRawNormalisedValueZSTANDARDVALUE: TFloatField;
    qRawNormalisedValueZACCEPTEDVALUE: TFloatField;
    qRawNormalisedValueZNORMALISEDVALUE: TFloatField;
    qRawDataZerrSAMPLENO: TWideStringField;
    qRawDataZerrFRAC: TWideStringField;
    qRawDataZerrISOSYSTEM: TWideStringField;
    qRawDataZerrVARIABLEID: TWideStringField;
    qRawDataZerrDATAVALUE: TFloatField;
    qRawDataZerrNORMALISINGSTANDARD: TWideStringField;
    qRawDataZerrSTANDARDVALUE: TFloatField;
    qRawDataZerrVARIABLENAME: TWideStringField;
    qRawErrTypeZSAMPLENO: TWideStringField;
    qRawErrTypeZFRAC: TWideStringField;
    qRawErrTypeZISOSYSTEM: TWideStringField;
    qRawErrTypeZVARIABLEID: TWideStringField;
    qRawErrTypeZDATAVALUE: TFloatField;
    qRawErrTypeZNORMALISINGSTANDARD: TWideStringField;
    qRawErrTypeZSTANDARDVALUE: TFloatField;
    qRawErrTypeZVARIABLENAME: TWideStringField;
    qRawDataPrecZSAMPLENO: TWideStringField;
    qRawDataPrecZFRAC: TWideStringField;
    qRawDataPrecZISOSYSTEM: TWideStringField;
    qRawDataPrecZVARIABLEID: TWideStringField;
    qRawDataPrecZDATAVALUE: TFloatField;
    qRawDataDMSAMPLENO: TWideStringField;
    qRawDataDMFRAC: TWideStringField;
    qRawDataDMISOSYSTEM: TWideStringField;
    qRawDataDMVARIABLEID: TWideStringField;
    qRawDataDMDATAVALUE: TFloatField;
    qRawDiscordanceSAMPLENO: TWideStringField;
    qRawDiscordanceFRAC: TWideStringField;
    qRawDiscordanceISOSYSTEM: TWideStringField;
    qRawDiscordanceVARIABLEID: TWideStringField;
    qRawDiscordanceDATAVALUE: TFloatField;
    qRawRefSAMPLENO: TWideStringField;
    qRawRefREFNUM: TIntegerField;
    qRawRefSOURCESHORT: TWideStringField;
    qRawDataDMerrSAMPLENO: TWideStringField;
    qRawDataDMerrFRAC: TWideStringField;
    qRawDataDMerrISOSYSTEM: TWideStringField;
    qRawDataDMerrVARIABLEID: TWideStringField;
    qRawDataDMerrDATAVALUE: TFloatField;
    qRawDataDMerrNORMALISINGSTANDARD: TWideStringField;
    qRawDataDMerrSTANDARDVALUE: TFloatField;
    qRawDataDMerrVARIABLENAME: TWideStringField;
    qRawAgePrefSAMPLENO: TWideStringField;
    qRawAgePrefFRAC: TWideStringField;
    qRawAgePrefISOSYSTEM: TWideStringField;
    qRawAgePrefVARIABLEID: TWideStringField;
    qRawAgePrefDATAVALUE: TFloatField;
    qRawSmpLocCOUNTRYABR: TWideStringField;
    qRawSmpLocCONTINENTID: TWideStringField;
    qRawSmpLocLONGITUDE: TFloatField;
    qRawSmpLocLATITUDE: TFloatField;
    qRawSmpLocELEVATION: TFloatField;
    qRawDataAgeerrSAMPLENO: TWideStringField;
    qRawDataAgeerrFRAC: TWideStringField;
    qRawDataAgeerrISOSYSTEM: TWideStringField;
    qRawDataAgeerrVARIABLEID: TWideStringField;
    qRawDataAgeerrDATAVALUE: TFloatField;
    qRawDataAgeerrNORMALISINGSTANDARD: TWideStringField;
    qRawDataAgeerrSTANDARDVALUE: TFloatField;
    qRawDataAgeerrVARIABLENAME: TWideStringField;
    qRecalcSmp: TSQLQuery;
    dsqRecalcSmp: TDataSource;
    dspRecalcSmp: TDataSetProvider;
    cdsRecalcSmp: TClientDataSet;
    dsRecalcSmp: TDataSource;
    qRecalcY: TSQLQuery;
    dsqRecalcY: TDataSource;
    cdsRecalcY: TClientDataSet;
    dsRecalcY: TDataSource;
    qRecalcStandardY: TSQLQuery;
    cdsRecalcStandardY: TClientDataSet;
    dsRecalcStandardValueY: TDataSource;
    qRecalcNormalisedY: TSQLQuery;
    cdsRecalcNormalisedY: TClientDataSet;
    dsRecalcNormalisedY: TDataSource;
    qRecalcAgePref: TSQLQuery;
    dsqRecalcAgePref: TDataSource;
    cdsRecalcAgePref: TClientDataSet;
    dsRecalcAgePref: TDataSource;
    qRecalcZ: TSQLQuery;
    dsqRecalcZ: TDataSource;
    cdsRecalcZ: TClientDataSet;
    dsRecalcZ: TDataSource;
    qRecalcSmpSAMPLENO: TWideStringField;
    qRecalcSmpFRAC: TWideStringField;
    cdsRecalcSmpSAMPLENO: TWideStringField;
    cdsRecalcSmpFRAC: TWideStringField;
    cdsRecalcSmpqRecalcZ: TDataSetField;
    cdsRecalcSmpqRecalcAgePref: TDataSetField;
    cdsRecalcSmpqRecalcNormalisedY: TDataSetField;
    cdsRecalcSmpqRecalcY: TDataSetField;
    qRecalcYSAMPLENO: TWideStringField;
    qRecalcYFRAC: TWideStringField;
    qRecalcYISOSYSTEM: TWideStringField;
    qRecalcYVARIABLEID: TWideStringField;
    qRecalcYDATAVALUE: TFloatField;
    qRecalcYNORMALISINGSTANDARD: TWideStringField;
    qRecalcYSTANDARDVALUE: TFloatField;
    qRecalcYVARIABLENAME: TWideStringField;
    cdsRecalcYSAMPLENO: TWideStringField;
    cdsRecalcYFRAC: TWideStringField;
    cdsRecalcYISOSYSTEM: TWideStringField;
    cdsRecalcYVARIABLEID: TWideStringField;
    cdsRecalcYDATAVALUE: TFloatField;
    cdsRecalcYNORMALISINGSTANDARD: TWideStringField;
    cdsRecalcYSTANDARDVALUE: TFloatField;
    cdsRecalcYVARIABLENAME: TWideStringField;
    cdsRecalcYqRecalcStandardY: TDataSetField;
    qRecalcStandardYACCEPTEDVALUE: TFloatField;
    qRecalcNormalisedYSAMPLENO: TWideStringField;
    qRecalcNormalisedYFRAC: TWideStringField;
    qRecalcNormalisedYISOSYSTEM: TWideStringField;
    qRecalcNormalisedYVARIABLEID: TWideStringField;
    qRecalcNormalisedYDATAVALUE: TFloatField;
    qRecalcNormalisedYNORMALISINGSTANDARD: TWideStringField;
    qRecalcNormalisedYSTANDARDVALUE: TFloatField;
    qRecalcNormalisedYACCEPTEDVALUE: TFloatField;
    qRecalcNormalisedYNORMALISEDVALUE: TFloatField;
    cdsRecalcNormalisedYSAMPLENO: TWideStringField;
    cdsRecalcNormalisedYFRAC: TWideStringField;
    cdsRecalcNormalisedYISOSYSTEM: TWideStringField;
    cdsRecalcNormalisedYVARIABLEID: TWideStringField;
    cdsRecalcNormalisedYDATAVALUE: TFloatField;
    cdsRecalcNormalisedYNORMALISINGSTANDARD: TWideStringField;
    cdsRecalcNormalisedYSTANDARDVALUE: TFloatField;
    cdsRecalcNormalisedYACCEPTEDVALUE: TFloatField;
    cdsRecalcNormalisedYNORMALISEDVALUE: TFloatField;
    qRecalcAgePrefSAMPLENO: TWideStringField;
    qRecalcAgePrefFRAC: TWideStringField;
    qRecalcAgePrefISOSYSTEM: TWideStringField;
    qRecalcAgePrefVARIABLEID: TWideStringField;
    qRecalcAgePrefDATAVALUE: TFloatField;
    cdsRecalcAgePrefSAMPLENO: TWideStringField;
    cdsRecalcAgePrefFRAC: TWideStringField;
    cdsRecalcAgePrefISOSYSTEM: TWideStringField;
    cdsRecalcAgePrefVARIABLEID: TWideStringField;
    cdsRecalcAgePrefDATAVALUE: TFloatField;
    cdsRecalcZSAMPLENO: TWideStringField;
    cdsRecalcZFRAC: TWideStringField;
    cdsRecalcZISOSYSTEM: TWideStringField;
    cdsRecalcZVARIABLEID: TWideStringField;
    cdsRecalcZDATAVALUE: TFloatField;
    cdsRecalcZNORMALISINGSTANDARD: TWideStringField;
    cdsRecalcZSTANDARDVALUE: TFloatField;
    cdsRecalcZVARIABLENAME: TWideStringField;
    cdsDatatRec: TIntegerField;
    cdsInitials: TClientDataSet;
    dsInitials: TDataSource;
    cdsInitialsInitial: TFloatField;
    cdsInitialsInitialError: TFloatField;
    cdsInitialsEpsilon: TFloatField;
    cdsInitialsEpsilonError: TFloatField;
    cdsInitialsSampleNo: TWideStringField;
    cdsInitialsFrac: TWideStringField;
    cdsInitialsi: TIntegerField;
    cdsInitialsAge: TFloatField;
    cdsInitialsAgePlus95: TFloatField;
    cdsInitialsAgeMinus95: TFloatField;
    qNew: TSQLQuery;
    cdsDataHfYmodeli: TFloatField;
    cdsInitialsYmodeli: TFloatField;
    cdsDataHfInitRatio: TFloatField;
    cdsDataHfInitRatioSigma: TFloatField;
    cdsDataHf176Lu177Hf: TFloatField;
    cdsDataHf176Lu177HfSigma: TFloatField;
    cdsDataHf176Hf177Hf: TFloatField;
    cdsDataHf176Hf177HfSigma: TFloatField;
    cdsDataHfyes: TClientDataSet;
    dsDataHfyes: TDataSource;
    cdsDataHfyesSampleNo: TWideStringField;
    cdsDataHfyesFrac: TWideStringField;
    cdsDataHfyesEpsilon: TFloatField;
    cdsDataHfyesEpsilonSigma: TFloatField;
    cdsDataHfyesPreferredAge: TFloatField;
    cdsDataHfyesPreferredAgeSigma: TFloatField;
    cdsDataHfyesIncludeYN: TWideStringField;
    cdsDataHfyesPercentConcordance: TFloatField;
    cdsDataHfyesTDM: TFloatField;
    cdsDataHfyesTDMSigma: TFloatField;
    cdsDataHfyesYmodeli: TFloatField;
    cdsDataHfyesInitRatio: TFloatField;
    cdsDataHfyesInitRatioSigma: TFloatField;
    cdsDataHfyes176Lu177Hf: TFloatField;
    cdsDataHfyes176Lu177HfSigma: TFloatField;
    cdsDataHfyes176Hf177Hf: TFloatField;
    cdsDataHfyes176Hf177HfSigma: TFloatField;
    cdsDataHfi: TIntegerField;
    qRawDataInclude: TSQLQuery;
    cdsRawDataInclude: TClientDataSet;
    dsRawDataInclude: TDataSource;
    cdsRawSmpqRawDataInclude: TDataSetField;
    qRawDataIncludeSAMPLENO: TWideStringField;
    qRawDataIncludeFRAC: TWideStringField;
    qRawDataIncludeISOSYSTEM: TWideStringField;
    qRawDataIncludeVARIABLEID: TWideStringField;
    qRawDataIncludeDATAVALUE: TFloatField;
    cdsRawDataIncludeSAMPLENO: TWideStringField;
    cdsRawDataIncludeFRAC: TWideStringField;
    cdsRawDataIncludeISOSYSTEM: TWideStringField;
    cdsRawDataIncludeVARIABLEID: TWideStringField;
    cdsRawDataIncludeDATAVALUE: TFloatField;
    cdsPeaks: TClientDataSet;
    dsPeaks: TDataSource;
    cdsPeaksPeakStep: TIntegerField;
    cdsPeaksPeakAge: TFloatField;
    cdsPeaksPeakValue: TFloatField;
    cdsPeaksPeakChange: TFloatField;
    qRecalcX: TSQLQuery;
    StringField25: TWideStringField;
    StringField26: TWideStringField;
    StringField27: TWideStringField;
    StringField28: TWideStringField;
    FloatField17: TFloatField;
    StringField29: TWideStringField;
    FloatField18: TFloatField;
    StringField30: TWideStringField;
    dsqRecalcX: TDataSource;
    cdsRecalcX: TClientDataSet;
    dsRecalcX: TDataSource;
    qRecalcStandardX: TSQLQuery;
    FloatField21: TFloatField;
    cdsRecalcStandardX: TClientDataSet;
    dsRecalcStandardValueX: TDataSource;
    qRecalcNormalisedX: TSQLQuery;
    StringField37: TWideStringField;
    StringField38: TWideStringField;
    StringField39: TWideStringField;
    StringField40: TWideStringField;
    FloatField22: TFloatField;
    StringField41: TWideStringField;
    FloatField23: TFloatField;
    FloatField24: TFloatField;
    FloatField25: TFloatField;
    cdsRecalcNormalisedX: TClientDataSet;
    dsRecalcNormalisedX: TDataSource;
    cdsRecalcSmpqRecalcNormalisedX: TDataSetField;
    cdsRecalcSmpqRecalcX: TDataSetField;
    cdsRecalcXqRecalcStandardX: TDataSetField;
    qRecalcDM: TSQLQuery;
    dsqRecalcDM: TDataSource;
    cdsRecalcDM: TClientDataSet;
    dsRecalcDM: TDataSource;
    cdsRecalcSmpqRecalcDM: TDataSetField;
    cdsRecalcDMSAMPLENO: TWideStringField;
    cdsRecalcDMFRAC: TWideStringField;
    cdsRecalcDMISOSYSTEM: TWideStringField;
    cdsRecalcDMVARIABLEID: TWideStringField;
    cdsRecalcDMDATAVALUE: TFloatField;
    cdsRecalcDMNORMALISINGSTANDARD: TWideStringField;
    cdsRecalcDMSTANDARDVALUE: TFloatField;
    cdsRecalcDMVARIABLENAME: TWideStringField;
    cdsRecalcNormalisedXSAMPLENO: TWideStringField;
    cdsRecalcNormalisedXFRAC: TWideStringField;
    cdsRecalcNormalisedXISOSYSTEM: TWideStringField;
    cdsRecalcNormalisedXVARIABLEID: TWideStringField;
    cdsRecalcNormalisedXDATAVALUE: TFloatField;
    cdsRecalcNormalisedXNORMALISINGSTANDARD: TWideStringField;
    cdsRecalcNormalisedXSTANDARDVALUE: TFloatField;
    cdsRecalcNormalisedXACCEPTEDVALUE: TFloatField;
    cdsRecalcNormalisedXNORMALISEDVALUE: TFloatField;
    cdsRecalcXSAMPLENO: TWideStringField;
    cdsRecalcXFRAC: TWideStringField;
    cdsRecalcXISOSYSTEM: TWideStringField;
    cdsRecalcXVARIABLEID: TWideStringField;
    cdsRecalcXDATAVALUE: TFloatField;
    cdsRecalcXNORMALISINGSTANDARD: TWideStringField;
    cdsRecalcXSTANDARDVALUE: TFloatField;
    cdsRecalcXVARIABLENAME: TWideStringField;
    dsRecalcInit: TDataSource;
    cdsRecalcInit: TClientDataSet;
    dsqRecalcInit: TDataSource;
    qRecalcInit: TSQLQuery;
    cdsRecalcSmpqRecalcInit: TDataSetField;
    cdsRecalcInitSAMPLENO: TWideStringField;
    cdsRecalcInitFRAC: TWideStringField;
    cdsRecalcInitISOSYSTEM: TWideStringField;
    cdsRecalcInitVARIABLEID: TWideStringField;
    cdsRecalcInitDATAVALUE: TFloatField;
    cdsRecalcInitNORMALISINGSTANDARD: TWideStringField;
    cdsRecalcInitSTANDARDVALUE: TFloatField;
    cdsRecalcInitVARIABLENAME: TWideStringField;
    qRecalcDMSAMPLENO: TWideStringField;
    qRecalcDMFRAC: TWideStringField;
    qRecalcDMISOSYSTEM: TWideStringField;
    qRecalcDMVARIABLEID: TWideStringField;
    qRecalcDMDATAVALUE: TFloatField;
    qRecalcDMNORMALISINGSTANDARD: TWideStringField;
    qRecalcDMSTANDARDVALUE: TFloatField;
    qRecalcDMVARIABLENAME: TWideStringField;
    qRecalcInitSAMPLENO: TWideStringField;
    qRecalcInitFRAC: TWideStringField;
    qRecalcInitISOSYSTEM: TWideStringField;
    qRecalcInitVARIABLEID: TWideStringField;
    qRecalcInitDATAVALUE: TFloatField;
    qRecalcInitNORMALISINGSTANDARD: TWideStringField;
    qRecalcInitSTANDARDVALUE: TFloatField;
    qRecalcInitVARIABLENAME: TWideStringField;
    qRecalcZSAMPLENO: TWideStringField;
    qRecalcZFRAC: TWideStringField;
    qRecalcZISOSYSTEM: TWideStringField;
    qRecalcZVARIABLEID: TWideStringField;
    qRecalcZDATAVALUE: TFloatField;
    qRecalcZNORMALISINGSTANDARD: TWideStringField;
    qRecalcZSTANDARDVALUE: TFloatField;
    qRecalcZVARIABLENAME: TWideStringField;
    qUpdateData: TSQLQuery;
    qVarVarISOTOPESYSTEM: TWideStringField;
    cdsVarVarISOTOPESYSTEM: TWideStringField;
    cdsQdmSmpqSmpDataX: TDataSetField;
    cdsNormalisedValueYSAMPLENO: TWideStringField;
    cdsNormalisedValueYFRAC: TWideStringField;
    cdsNormalisedValueYISOSYSTEM: TWideStringField;
    cdsNormalisedValueYVARIABLEID: TWideStringField;
    cdsNormalisedValueYDATAVALUE: TFloatField;
    cdsNormalisedValueYNORMALISINGSTANDARD: TWideStringField;
    cdsNormalisedValueYSTANDARDVALUE: TFloatField;
    cdsNormalisedValueYACCEPTEDVALUE: TFloatField;
    cdsSmpDataYqStandardValueY: TDataSetField;
    cdsTable1test: TWideStringField;
    SQLMonitor1: TSQLMonitor;
    qRawSmpLocLITHOLOGY: TWideStringField;
    qRawSmpLocLITHCLASS: TWideStringField;
    cdsRawSmpLocLITHOLOGY: TWideStringField;
    cdsRawSmpLocLITHCLASS: TWideStringField;
    cdsDataChem: TClientDataSet;
    cdsDataChemi: TIntegerField;
    cdsDataChemSampleNo: TWideStringField;
    cdsDataChemFrac: TWideStringField;
    cdsDataChemPreferredAge: TFloatField;
    cdsDataChemPreferredAgeSigma: TFloatField;
    cdsDataChemPercentConcordance: TFloatField;
    cdsDataChemIncludeYN: TWideStringField;
    dsDataChem: TDataSource;
    cdsDataChemVar1: TFloatField;
    cdsDataChemVar1Sigma: TFloatField;
    cdsDataChemVar2: TFloatField;
    cdsDataChemVar2Sigma: TFloatField;
    cdsDataChemVar3: TFloatField;
    cdsDataChemVar3Sigma: TFloatField;
    qRawSmpREGASSOCID: TWideStringField;
    cdsRawSmpREGASSOCID: TWideStringField;
    qRecalcSmpREGASSOCID: TWideStringField;
    cdsRecalcSmpREGASSOCID: TWideStringField;
    qSmpDataXSAMPLENO: TWideStringField;
    qSmpDataXFRAC: TWideStringField;
    qSmpDataXISOSYSTEM: TWideStringField;
    qSmpDataXVARIABLEID: TWideStringField;
    qSmpDataXDATAVALUE: TFloatField;
    qSmpDataXNORMALISINGSTANDARD: TWideStringField;
    qSmpDataXSTANDARDVALUE: TFloatField;
    qSmpDataXVARIABLENAME: TWideStringField;
    qSmpDataXREGASSOCID: TWideStringField;
    cdsSmpDataXREGASSOCID: TWideStringField;
    qRecalcSmpISOSYSTEM: TWideStringField;
    cdsRecalcSmpISOSYSTEM: TWideStringField;
    qRawAgePrefREGASSOCID: TWideStringField;
    cdsRawAgePrefREGASSOCID: TWideStringField;
    qRawDataZREGASSOCID: TWideStringField;
    cdsRawDataZREGASSOCID: TWideStringField;
    qRawDataYREGASSOCID: TWideStringField;
    cdsRawDataYREGASSOCID: TWideStringField;
    qRawDataXREGASSOCID: TWideStringField;
    cdsRawDataXREGASSOCID: TWideStringField;
    qRawDataDMREGASSOCID: TWideStringField;
    cdsRawDataDMREGASSOCID: TWideStringField;
    cdsDataZoneID: TWideStringField;
    cdsDataHfZoneID: TWideStringField;
    cdsDataHfyesZoneID: TWideStringField;
    cdsDataChemZoneID: TWideStringField;
    qRawSmpZONEID: TWideStringField;
    cdsRawSmpZONEID: TWideStringField;
    qIsoModelsMODELNAME: TWideStringField;
    cdsIsoModelsMODELNAME: TWideStringField;
    dsIsoModelApproach: TDataSource;
    cdsIsoModelApproach: TClientDataSet;
    dspIsoModelApproach: TDataSetProvider;
    qIsoModelApproach: TSQLQuery;
    WideStringField5: TWideStringField;
    WideStringField6: TWideStringField;
    FloatField29: TFloatField;
    FloatField30: TFloatField;
    FloatField31: TFloatField;
    FloatField32: TFloatField;
    FloatField33: TFloatField;
    WideStringField7: TWideStringField;
    WideStringField8: TWideStringField;
    qIsoModelsMODELTYPEID: TWideStringField;
    qIsoModelsMODELTYPE: TWideStringField;
    cdsIsoModelsMODELTYPEID: TWideStringField;
    cdsIsoModelsMODELTYPE: TWideStringField;
    qIsoModelApproachMODELTYPEID: TWideStringField;
    qIsoModelApproachMODELTYPE: TWideStringField;
    cdsIsoModelApproachMODELID: TWideStringField;
    cdsIsoModelApproachISOSYSTEM: TWideStringField;
    cdsIsoModelApproachMODELTYPEID: TWideStringField;
    cdsIsoModelApproachMODELTYPE: TWideStringField;
    cdsIsoModelApproachMODELPARAM1: TFloatField;
    cdsIsoModelApproachMODELPARAM2: TFloatField;
    cdsIsoModelApproachMODELPARAM3: TFloatField;
    cdsIsoModelApproachMODELPARAM4: TFloatField;
    cdsIsoModelApproachMODELPARAM5: TFloatField;
    cdsIsoModelApproachISOSYSTEMNAME: TWideStringField;
    cdsIsoModelApproachMODELNAME: TWideStringField;
    qIsoSystem: TSQLQuery;
    qIsoSystemISOSYSTEM: TWideStringField;
    qIsoSystemISOSYSTEMNAME: TWideStringField;
    qIsoSystemISOSYSNO: TIntegerField;
    qIsoSystemDECAYCONST1: TFloatField;
    qIsoSystemDECAYCONST2: TFloatField;
    qIsoSystemISOTOPECONSTANT: TFloatField;
    dspIsoSystem: TDataSetProvider;
    cdsIsoSystem: TClientDataSet;
    cdsIsoSystemISOSYSTEM: TWideStringField;
    cdsIsoSystemISOSYSTEMNAME: TWideStringField;
    cdsIsoSystemISOSYSNO: TIntegerField;
    cdsIsoSystemDECAYCONST1: TFloatField;
    cdsIsoSystemDECAYCONST2: TFloatField;
    cdsIsoSystemISOTOPECONSTANT: TFloatField;
    dsIsoSystem: TDataSource;
  private
    { Private declarations }
  public
    { Public declarations }
    procedure CalculateConcordiaForAge(Age : double; var t207235 : double;
                                  var t206238 : double; var t207206 : double;
                                  var t238206 : double);
    procedure ConstructRawDataSampleQuery;
    procedure SubmitNewIsoInitRecord(tRecordID : integer;
                                     tAge, tInitial, tInitialError,
                                     tEpsilon, tEpsilonError : double;
                                 var WasSuccessful : boolean);
    function DM_Age(tx, ty, DC, MP1, MP2, MP3, AgeTolerance : double) : double;
    function DM_Age_Error(tx, ty, txe, tye, TMult, DC, MP1, MP2, MP3, AgeTolerance : double) : double;
    procedure UpdateSmpData(tSampleNo,tFrac,tIsoSystem,tVariableID,tTechAbr : string;
                            RevisedDataValue : double;
                        var WasSuccessful : boolean);
  end;

// Procs
  function dmdDV: TdmdDV;

implementation
{$R *.dfm}

uses
  IWInit,
  ServerController,
  DVIW_constants, usrIW_dm, UserSessionUnit;


function dmdDV: TdmdDV;
begin
  Result := TIWUserSession(WebApplication.Data).dmdDV;
end;

procedure TdmdDV.CalculateConcordiaForAge(Age : double; var t207235 : double;
                                  var t206238 : double; var t207206 : double;
                                  var t238206 : double);
const
  DecayConst235U = 9.8485e-10;
  DecayConst238U = 1.55125e-10;
  Constant238235 = 137.88;
begin
  t207235 := Exp(DecayConst235U*Age)-1.0;
  t206238 := Exp(DecayConst238U*Age)-1.0;
  if (Age > 0.00001) then t207206 := (1.0/Constant238235) * (t207235/t206238)
                     else t207206 := 0.046045;
  if (t206238 > 0.0) then  t238206 := 1.0/t206238
                     else t238206 := 0.0;
end;

procedure TdmdDV.ConstructRawDataSampleQuery;
var
  i : integer;
begin
  dmdDV.qRawSmp.Close;
  dmdDV.qRawSmp.SQL.Clear;
  dmdDV.qRawSmp.SQL.Add('SELECT DISTINCT SMPDATA.SAMPLENO, SMPDATA.FRAC,');
  dmdDV.qRawSmp.SQL.Add('  SMPFRAC.ZONEID,');
  dmdDV.qRawSmp.SQL.Add('  VARREGASSOC.REGASSOCID ');
  dmdDV.qRawSmp.SQL.Add('FROM SMPDATA,SMPLOC,VARREGASSOC,SMPFRAC ');
  if (UserSession.IncludeTerraneValues) then
  begin
    dmdDV.qRawSmp.SQL.Add(',SMPREG,ISOPROVTERR ');
  end;
  dmdDV.qRawSmp.SQL.Add('WHERE SMPDATA.SAMPLENO=SMPLOC.SAMPLENO');
  dmdDV.qRawSmp.SQL.Add('AND VARREGASSOC.REGASSOCID=:RegAssocID');
  dmdDV.qRawSmp.SQL.Add('AND SMPFRAC.SAMPLENO=SMPDATA.SAMPLENO');
  dmdDV.qRawSmp.SQL.Add('AND SMPFRAC.FRAC=SMPDATA.FRAC');
  //dmdDV.qRawSmp.SQL.Add('AND (SMPDATA.ISOSYSTEM=:IsotopeSystem');
  //if ((UserSession.UnitSender = usIndividualAgeChem) or (UserSession.UnitSender = usMultipleAgeChem))
  //then dmdDV.qRawSmp.SQL.Add('OR SMPDATA.ISOSYSTEM='+''''+'UPb'+'''');
  //dmdDV.qRawSmp.SQL.Add('OR SMPDATA.ISOSYSTEM='+''''+'NA'+''''+')');
  if (UserSession.IncludeSampleValues and (UserSession.SampleValues.Count=0)) then
  begin
    UserSession.IncludeSampleValues := false;
  end;
  if (UserSession.IncludeSampleZoneValues and (UserSession.SampleZoneValues.Count=0)) then
  begin
    UserSession.IncludeSampleZoneValues := false;
  end;
  if (UserSession.IncludeContinentValues) then
  begin
    dmdDV.qRawSmp.SQL.Add('AND ( SMPLOC.CONTINENTID = '+''''+UserSession.ContinentValues.Strings[0]+'''');
    if (UserSession.ContinentValues.Count >1) then
    begin
      for i := 2 to UserSession.ContinentValues.Count do
      begin
        dmdDV.qRawSmp.SQL.Add('OR SMPLOC.CONTINENTID = '+''''+UserSession.ContinentValues.Strings[i-1]+'''');
      end;
    end;
    dmdDV.qRawSmp.SQL.Add(' ) ');
  end;
  if (UserSession.IncludeAreaValues) then
  begin
    dmdDV.qRawSmp.SQL.Add('AND ( SMPLOC.COUNTRYABR = '+''''+UserSession.AreaValues.Strings[0]+'''');
    if (UserSession.AreaValues.Count >1) then
    begin
      for i := 2 to UserSession.AreaValues.Count do
      begin
        dmdDV.qRawSmp.SQL.Add('OR SMPLOC.COUNTRYABR = '+''''+UserSession.AreaValues.Strings[i-1]+'''');
      end;
    end;
    dmdDV.qRawSmp.SQL.Add(' ) ');
  end;
  if (UserSession.IncludeSampleValues) then
  begin
    dmdDV.qRawSmp.SQL.Add('AND ( SMPDATA.SAMPLENO = '+''''+UserSession.SampleValues.Strings[0]+'''');
    if (UserSession.SampleValues.Count >1) then
    begin
      for i := 2 to UserSession.SampleValues.Count do
      begin
        dmdDV.qRawSmp.SQL.Add('OR SMPDATA.SAMPLENO = '+''''+UserSession.SampleValues.Strings[i-1]+'''');
      end;
    end;
    dmdDV.qRawSmp.SQL.Add(' ) ');
  end;
  if (not UserSession.IncludeSampleValues) then
  begin
    dmdDV.qRawSmp.SQL.Add('AND SMPDATA.SAMPLENO >= '+''''+UserSession.SampleStartFrom+'''');
    dmdDV.qRawSmp.SQL.Add('AND SMPDATA.SAMPLENO <= '+''''+UserSession.SampleEndWith+'''');
  end;
  if (UserSession.IncludeSampleZoneValues) then
  begin
    dmdDV.qRawSmp.SQL.Add('AND ( SMPFRAC.ZONEID = '+''''+UserSession.SampleZoneValues.Strings[0]+'''');
    if (UserSession.IncludeSampleZoneValues and (UserSession.SampleZoneValues.Count >1)) then
    begin
      for i := 2 to UserSession.SampleZoneValues.Count do
      begin
        dmdDV.qRawSmp.SQL.Add('OR SMPFRAC.ZONEID = '+''''+UserSession.SampleZoneValues.Strings[i-1]+'''');
      end;
    end;
    dmdDV.qRawSmp.SQL.Add(' ) ');
  end;
  if (UserSession.IncludeReferenceValues) then
  begin
    dmdDV.qRawSmp.SQL.Add('AND ( SMPDATA.REFNUM = '+''''+UserSession.ReferenceValues.Strings[0]+'''');
    if (UserSession.ReferenceValues.Count >1) then
    begin
      for i := 2 to UserSession.ReferenceValues.Count do
      begin
        dmdDV.qRawSmp.SQL.Add('OR SMPDATA.REFNUM = '+''''+UserSession.ReferenceValues.Strings[i-1]+'''');
      end;
    end;
    dmdDV.qRawSmp.SQL.Add(' ) ');
  end;
  if UserSession.IncludeCoordinates then
  begin
    dmdDV.qRawSmp.SQL.Add('AND SMPLOC.LATITUDE <= 90.0');
    dmdDV.qRawSmp.SQL.Add('AND SMPLOC.LATITUDE <= '+UserSession.NELat);
    dmdDV.qRawSmp.SQL.Add('AND SMPLOC.LONGITUDE <= '+UserSession.NELon);
    dmdDV.qRawSmp.SQL.Add('AND SMPLOC.LATITUDE >= '+UserSession.SWLat);
    dmdDV.qRawSmp.SQL.Add('AND SMPLOC.LONGITUDE >= '+UserSession.SWLon);
  end;
  if (UserSession.IncludeTerraneValues) then
  begin
    dmdDV.qRawSmp.SQL.Add('and smpreg.sampleno=smploc.sampleno');
    dmdDV.qRawSmp.SQL.Add('and smpreg.recordid=isoprovterr.recordid');
    //dmdDV.qRawSmp.SQL.Add('and smpreg.recordid=isoprovterr.recordid');
    dmdDV.qRawSmp.SQL.Add('AND ( ISOPROVTERR.DOMAINID = '+''''+UserSession.TerraneValues.Strings[0]+'''');
    if (UserSession.TerraneValues.Count >1) then
    begin
      for i := 2 to UserSession.TerraneValues.Count do
      begin
        dmdDV.qRawSmp.SQL.Add('OR ISOPROVTERR.DOMAINID = '+''''+UserSession.TerraneValues.Strings[i-1]+'''');
      end;
    end;
    dmdDV.qRawSmp.SQL.Add(' ) ');
  end;
  dmdDV.qRawSmp.SQL.Add('ORDER BY SMPDATA.SAMPLENO, SMPDATA.FRAC');
  //dmUser.SetDeveloperData('qRawSmp construct');
  //dmUser.SetDeveloperData(dmdDV.qRawSmp.SQL.Text);
end;

procedure TdmdDV.SubmitNewIsoInitRecord(tRecordID : integer;
                                        tAge, tInitial, tInitialError,
                                        tEpsilon, tEpsilonError : double;
                                        var WasSuccessful : boolean);
const
  zero = 0;
var
  TD: TDBXTransaction;
  tFullAge, tempinitialage,
  tempinitial, tempinitialerror,
  tempepsilon, tempepsilonerror : double;
begin
  UserSession.WhereAmI := 'NewIsoInitRecord start';
  try
    UserSession.WhereAmI := 'Start Insert new isoinit record';
    dmdDV.qNew.SQL.Clear;
    dmdDV.qNew.SQL.Add('INSERT INTO ISOINIT');
    dmdDV.qNew.SQL.Add('(RECORDID, INITRATIO, INITRATIOERROR, EPSILON, EPSILONERROR)');
    dmdDV.qNew.SQL.Add('VALUES ('+IntToStr(tRecordID)+', '+FormatFloat('###0.000000',tinitial)+', ');
    dmdDV.qNew.SQL.Add(FormatFloat('###0.000000',tinitialerror)+', ');
    dmdDV.qNew.SQL.Add(FormatFloat('####0.0000',tepsilon)+', ');
    dmdDV.qNew.SQL.Add(FormatFloat('####0.0000',tepsilonerror)+')');
    //dmUser.SetDeveloperData(dmdDV.qNew.SQL.Text);
    if not dmdDV.sqlcDateView.InTransaction then
    begin
      TD := dmdDV.sqlcDateView.BeginTransaction(TDBXIsolations.ReadCommitted);
      try
        dmdDV.qNew.ExecSQL(false);
        dmdDV.sqlcDateView.CommitFreeAndNil(TD); //on success, commit the changes
        WasSuccessful := true;
      except
        dmdDV.sqlcDateView.RollbackFreeAndNil(TD); //on failure, undo the changes
        WasSuccessful := false;
      end;
    end;
  except
  end;
  UserSession.WhereAmI := 'NewIsoInitRecord end';
end;

function TdmdDV.DM_Age(tx, ty, DC, MP1, MP2, MP3, AgeTolerance : double) : double;
const
  MaxIterations = 50;
var
  i                  : integer;
  temp, temp1       : double;
  DMX1, DMY1, DMY2, Difference,
  AgeMax, ApproxAge :  double;
  ThisDone          :  Boolean;
begin
  if (MP3 > 0.0) then
  begin
    if (MP1 <> 0.0) then
    begin
      ThisDone := false;
      i := 0;
      AgeMax := 4.60E9;
      repeat
        DMX1 := ty-tx*(Exp(DC*AgeMax)-1.0);
        DMY1 := MP1*(AgeMax)*(AgeMax)
            + MP2*(AgeMax)
            + MP3;
        DMY2 := (MP2)+tx*DC *(Exp(DC*AgeMax));
        DMY2 := DMY2+2.0*MP1*AgeMax;
        DMY1 := DMY1-DMX1;
        if (DMY2 <> 0.0) then
          ApproxAge := AgeMax-DMY1/DMY2
        else begin
          ApproxAge := 1.0e6;
          i := MaxIterations + 1;
        end;
        Difference := Abs(AgeMax-ApproxAge);
        AgeMax := ApproxAge;
        i := i+1;
        if (Difference < AgeTolerance) then ThisDone := true;
        if (i > MaxIterations) then
        begin
          AgeMax := 9999.0E6;
          ThisDone := true;
        end;
      until ThisDone;
    end;
    if ((MP1 = 0.0) and (MP2 > 0.0)) then
    begin
      temp := ((ty-MP3)/(tx-MP2) + 1.0);
      if (temp>0.0) then temp1 := ln(temp)
                    else temp1 := 0.0;
      AgeMax := (temp1/DC);
    end;
    DM_Age := AgeMax/1.0E6;
  end else
  begin
    DM_Age := 9999.99;
  end;
end;


function TdmdDV.DM_Age_Error(tx, ty, txe, tye, TMult, DC, MP1, MP2, MP3, AgeTolerance : double) : double;
var
  tage, tplus1,
  tminus1,
  t1, t2    : double;
begin
  t1 := txe;
  t2 := tye;
  if (t1 <= 0.0) then t1 := 1.0e-5;
  if (t2 <= 0.0) then t2 := 1.0e-5;
  tage := dmdDV.DM_Age(tx,ty,DC,MP1,MP2,MP3,AgeTolerance);
  tplus1 := dmdDV.DM_Age(tx+t1*TMult,ty+t2*TMult,DC,MP1,MP2,MP3,AgeTolerance);
  tminus1 := dmdDV.DM_Age(tx-t1*TMult,ty-t2*TMult,DC,MP1,MP2,MP3,AgeTolerance);
  DM_Age_Error := Sqrt(((tplus1-tage)*(tplus1-tage)+(tage-tminus1)*(tage-tminus1))+0.000001);
end;


procedure TdmdDV.UpdateSmpData(tSampleNo,tFrac,tIsoSystem,tVariableID,tTechAbr : string;
                               RevisedDataValue : double;
                           var WasSuccessful : boolean);
const
  zero = 0;
var
  TD: TDBXTransaction;
begin
  UserSession.WhereAmI := 'Start UpdateSmpData start';
  //try
    UserSession.WhereAmI := 'Start Update SMPDATA';
    dmdDV.qUpdateData.SQL.Clear;
    dmdDV.qUpdateData.SQL.Add('UPDATE SMPDATA');
    dmdDV.qUpdateData.SQL.Add('SET SMPDATA.DATAVALUE = '+FormatFloat('######.#######',RevisedDataValue));
    dmdDV.qUpdateData.SQL.Add('WHERE SMPDATA.SAMPLENO = '+quotedstr(tSampleNo));
    dmdDV.qUpdateData.SQL.Add('AND SMPDATA.FRAC = '+quotedstr(tFrac));
    dmdDV.qUpdateData.SQL.Add('AND SMPDATA.ISOSYSTEM = '+quotedstr(tIsoSystem));
    dmdDV.qUpdateData.SQL.Add('AND SMPDATA.VARIABLEID = '+quotedstr(tVariableID));
    //dmdDV.qUpdateData.SQL.Add('AND SMPDATA.TECHABR = '+quotedstr(tTechAbr));
    //dmUser.SetDeveloperData(dmdDV.qUpdateData.SQL.Text);
      TD := dmdDV.sqlcDateView.BeginTransaction(TDBXIsolations.ReadCommitted);
      try
        dmdDV.qUpdateData.ExecSQL(false);
        dmdDV.sqlcDateView.CommitFreeAndNil(TD); //on success, commit the changes
        WasSuccessful := true;
      except
        dmdDV.sqlcDateView.RollbackFreeAndNil(TD); //on failure, undo the changes
        WasSuccessful := false;
      end;
  //except
  //end;
  UserSession.WhereAmI := 'UpdateSmpData end';
end;




end.
